### ISSUE TITLE
Standardize Context

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/output-renderer-interface#12]
Currently, the context supplied for rendering, i.e. via [`TemplateInterface#render()`], can be anything. This isn't very usable, since a lot of checking and guesswork has to be done by the consumer.

Standardize this to be a `ContainerInterface|array`.

[`TemplateInterface#render()`]: https://github.com/Dhii/output-renderer-interface/blob/develop/src/TemplateInterface.php#L33

**Comment by mecha** [comment]
Agree with this 👍
