### ISSUE TITLE
Lost Hierarchy

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/output-renderer-interface#3]
The latest [`BlockInterface`] no longer extends [`RendererInterface`], because in the current state of things it would break LSP: `BlockInterface` would have to cater for an optional context argument, which it never uses. Also, their intended purpose is completely different: `BlockInterface` implementations should contain all data that is necessary to produce meaningful output, while `RendererInterface` implementations can be re-used multiple times with different context.

This calls for a unifying interface: something that does not require a context to render, and yet is not required to be stringable. `BlockInterface` can extend that to become stringable, and `RendererInterface` can extend that to accept an optional context. This would allow a generic set of exceptions to exist, perhaps implementing a new `RenderableAwareInterface`.

[`RendererInterface`]:                                 src/RendererInterface.php
[`BlockInterface`]:                                       https://github.com/Dhii/output-block-interface/blob/f4370566a22ca3753094eee9e406f3bd75e58a49/src/BlockInterface.php#L12

**Comment by XedinUnknown** [comment]
On the other hand, despite both currently having a `render()` method, perhaps the two are completely different things with a different purpose. From this perspective, `BlockInterface` is something that renders self, and `RendererInterface` is something that renders something else; the name of the `render()` method is simply a "coincidence".

However, from another perspective, on the interface level, perhaps it doesn't matter what the instances render: whether its themselves or something else, they produce output; one with a context, and one without.

**Comment by mecha** [comment]
I like the definitions that you gave for `BlockInterface` and for `RendererInterface`. The distinction is quite clear in that regard: one renders itself and depends on its own state as context, while the other renders something else as context and can depend on its state as configuration.

As such, I'd recommend `RenderableInterface` be renamed to `RenderCapableInterface`, for consistency with other interfaces. Being called "renderable" implies that the interface represents an object that can render itself, which is not necessarily the case. It might have enough information in its state to render something else. I recommend that we leave the "self render" concept reserved for `BlockInterface`.

**Comment by XedinUnknown** [comment]
@mecha, my point is that this distinction with regard to what the object will render (itself, or something else) is out of the interface scope. Instead, the interfaces may simply describe that one renders without context, and the other - with context.

About `RenderCapableInterface`, this would make related names even longer, i.e. `RenderCapableAwareRenderExceptionInterface`.

**Comment by mecha** [comment]
If I had to choose between long names and correct names, I'd probably go with correct. Especially if the difference is only 3 letters (`RenderableAwareRenderExceptionInterface`).

**Comment by XedinUnknown** [comment]
Fair enough.

**Comment by XedinUnknown** [comment]
Fixed.
